version: '3'
# TEST DEPLOY
services:
    db:
        container_name: "baang_db"
        image: mysql:8
        volumes:
            - './docker/db:/docker-entrypoint-initdb.d' # Place init .sql or .sql.gz file(s) here.
            #- './docker-data/db:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'P455W0RD'
        ports:
            - '3306:3306'

    mail:
        container_name: "baang_mail"
        image: tophfr/mailcatcher
        ports:
            - '1080:80'

    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
            args:
                - DOCKER_UID=${DOCKER_UID:-1000}
                - DOCKER_GID=${DOCKER_GID:-1000}
        container_name: "baang_php"
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            #- ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini #uncomment to activate
            # - ~/.ssh/:/root/.ssh/
        environment:
            PHP_IDE_CONFIG: 'serverName=localhost:80' # phpStorm->Settings->PHP->Servers[Name:]

    nginx:
        image: nginx:1-alpine
        container_name: "baang_nginx"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            # - ./docker/ssl/:/etc/ssl/docker/
            #- './docker-config/php-xdebug-phpstorm.ini:/etc/php/xdebug-settings.ini'
        ports:
            - "80:80"
            - "443:443"
